config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :stocks, except: [:destroy] do
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:show]

  resources :users, only: [:show, :edit, :update, :destroy, :index]

  get 'dashboard', to: 'users#dashboard'

  get 'dashboard/wallet', to: 'users#user_wallet'

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  validates :price, presence: true
  validates :quantity, presence: true
  validates :amount, presence: true
  validate :check_user_credit
  validate :check_user_wallet_stock_quantity

  before_validation :calcule_amount
  after_save :update_credit
  after_save :update_user_wallet

  private

  def calcule_amount
    self.amount = self.price * self.quantity
  end

  def update_credit
    self.user.credits -= self.amount
    self.user.save
  end

  def update_user_wallet
    user = self.user
    if user.wallet[self.stock_id.to_s].present?
      user.wallet[self.stock_id.to_s] += self.quantity
    else
      user.wallet[self.stock_id.to_s] = self.quantity
    end
    user.save
  end

  def check_user_credit
    errors.add(:user_insuficient_credit, 'insuficient credits') if self.user.credits < self.amount
  end

  def check_user_wallet_stock_quantity
    wallet_quantity = self.user.wallet[self.stock_id.to_s] || 0
    errors.add(:insuficient_stock_amount, 'insuficient stock amount') if wallet_quantity + self.quantity < 0
  end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :stock

  validates :price, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :price_histories
  has_many :orders

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true

  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_stock_name,
    against: [ :name, :fullname ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :stocks, through: :orders
  devise :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  validates :username, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.username = auth.info.name
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def invested_credits
    invested_credits = 0
    if self.wallet
      self.wallet.each do |key, value|
        stock = Stock.find(key.to_i)
        invested_credits += value * stock.price
      end
      invested_credits
    else
      invested_credits
    end
  end

  def total
    self.credits + self.invested_credits
  end

  def number_of_stocks
    i = 0
    self.wallet.each do |key, value|
      value > 0 ? i += 1 : i += 0
    end
    i
  end

  def calculate_level
    case self.experience
    when 0..19
      level = 1
    when 20..39
      level = 2
    when 40..79
      level = 3
    when 80..159
      level = 4
    when 160..319
      level = 5
    when 160..319
      level = 6
    end
    return level
  end

  def calculate_maxhp
    case self.calculate_level
    when 1
      maxhp = 20
    when 2
      maxhp = 40
    when 3
      maxhp = 80
    when 4
      maxhp = 160
    when 5
      maxhp = 320
    when 6
      maxhp = 640
    end
    return maxhp
  end

  def calculate_range
    quotient = (self.experience.to_f / self.calculate_maxhp.to_f) * 100
    case quotient
    when 0..25
      range = "a"
    when 26..49
      range = "b"
    when 50..75
      range = "c"
    when 76..99
      range = "d"
    end
    return range
  end

  def evolution
    (self.total - 1000) / 100
  end

  def ranking
    users = User.all.sort_by(&:total).reverse!
    i = 1
    users.each_with_index do |user, index|
      if  user == self
        i += index
      end
    end
    return i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @stock = Stock.find(params[:stock_id])
    @order.user = current_user
    @order.stock = @stock
    @order.price = @stock.price
    level = current_user.calculate_level
    if @order.save
      current_user.experience += 5
      current_user.save
      if level != current_user.calculate_level
        flash[:notice] = "YAY! Level UP! Congratulations! : )"
      else
        flash[:notice] = "Congratulations! #{@order.quantity.abs} #{@order.stock.name} #{@order.quantity.negative? ? 'removed from' : 'added to' } your wallet."
      end
      redirect_to dashboard_wallet_path
    else
      # Caso ela nao seja salva, retorna para a pagina anterior com uma mensagem de erro
      flash[:notice] = 'Something wrong happened.'
      render 'stocks/show'
    end

  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @user = current_user
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update]

  def index
    if params[:query].present?
      @stocks = Stock.search_by_stock_name(params[:query])
    else
      # @stocks = Stock.all.sort_by { |stock| stock.price }.reverse!
      @stocks = Stock.all.sort_by { |stock| (stock.variation.gsub!(",",".").to_f) }.reverse!

    end
  end

  def show
    @order = Order.new

  end

  def create
    @stock = Stock.new(stock_params)
    @stock.user = current_user
  end

  def edit
  end

  def update
    if @stock.update(stock_params)
      redirect_to @stock, notice: 'Stock was successfully updated.'
    else
      render :edit
    end
  end

  private

  def stock_params
    params.require(:stock).permit(:price, :name)
  end

  def set_stock
    @stock = Stock.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all.sort_by(&:total).reverse
  end

  def dashboard
    # @stocks = current_user.stocks
    # @user = current_user
    @wallet = current_user.wallet
    @orders = current_user.orders
  end

  def orders
    current_user.orders
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def user_wallet
    @wallet = current_user.wallet
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Stock Game</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="logo">
    <h1>PlayTrade
      <%#= image_tag("https://image.flaticon.com/icons/png/128/1825/1825576.png", height: "50", width: "50") %>
    </h1>
  </div>
  <div class="content-typed">
    <div><p>Let's</p></div><div class="typed_home"></div>
  </div>

  <div class="content">
    <div class="content__container">
      <ul class="content__container__list">
        <li class="content__container__list__item"><%= link_to "START", dashboard_path, class: "snip1562" %></li>
        <li class="content__container__list__item"><%= link_to "START", dashboard_path, class: "snip1562" %></li>
        <li class="content__container__list__item"><%= link_to "START", dashboard_path, class: "snip1562" %></li>
        <li class="content__container__list__item"><%= link_to "START", dashboard_path, class: "snip1562" %></li>
      </ul>
    </div>
  </div>



  </div>
</div>

<%= javascript_pack_tag 'typed_words' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links <%= params[:tab] == 'stock' ? 'active' : '' %>">
    <%= link_to stocks_path(tab: 'stock'), class: "button-x" do %>
      <i class="fas fa-store"></i>
    <% end %>
  </div>
  <div class="footer-links <%= params[:tab] == 'wallet' ? 'active' : '' %>">
    <%= link_to dashboard_wallet_path(tab: 'wallet'), class: "button-x" do %>
     <i class="fas fa-wallet"></i>
    <% end %>
  </div>
  <div class="footer-links <%= params[:tab] == 'users' ? 'active' : '' %>">
    <%= link_to users_path(tab: 'users'), class: "button-x" do %>
      <i class="fas fa-users"></i>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
  <h5>PlayTrade</h5>
  </div>
  <% if user_signed_in? %>
    <div class="nav-item dropdown">
      <% if current_user.photo.file.nil? %>
        <%= image_tag 'https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" } %>
      <% else %>
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
          <div class="MenuItem" role="separator"></div>
        <%= link_to 'Profile', edit_user_path(current_user), class: "dropdown-item" %>
          <div class="MenuItem" role="separator"></div>
        <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
          <div class="MenuItem" role="separator"></div>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% else %>
    <div class="nav-item">
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    </div>
  <% end %>
</div>

app/views/stocks/_new_order.html.erb
 <%= simple_form_for [stock, order] do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <%= f.error :user_insuficient_credit %>
                <div class="form-inputs d-flex justify-content-center m-3">
                  <%= f.input :quantity %>
                </div>
                <div class="form-actions d-flex justify-content-center">
                  <%= f.button :submit, class: 'btn confirm'%>
                </div>
            <% end %>

app/views/stocks/_quantity.js.erb
const plusButton = document.getElementById('button-plus');
const minusButton = document.getElementById('button-minus');

const stockInvested = document.getElementById('stock-invested');
const stockQuantity = document.getElementById('stock-quantity');

const orderQuantity = document.getElementById('order_quantity');
orderQuantity.value = 0

const currentCredits = document.getElementById('user-credits');



const price = '<%= @stock.price %>';

plusButton.addEventListener('click', (event) => {
  stockQuantity.innerText = parseInt(stockQuantity.innerText, 10) + 1
  stockInvested.innerText = (parseFloat(stockInvested.innerText, 10) + parseFloat(price, 10)).toFixed(2)
  orderQuantity.value = parseInt(orderQuantity.value, 10) + 1
  currentCredits.innerText = (parseFloat(currentCredits.innerText, 10) - parseFloat(price, 10)).toFixed(2)


});

minusButton.addEventListener('click', (event) => {

    stockQuantity.innerText = parseInt(stockQuantity.innerText, 10) - 1
    stockInvested.innerText = (parseFloat(stockInvested.innerText, 10) - parseFloat(price, 10)).toFixed(2)
    orderQuantity.value = parseInt(orderQuantity.value, 10) - 1
    currentCredits.innerText = (parseFloat(currentCredits.innerText, 10) + parseFloat(price, 10)).toFixed(2)



  });

app/views/stocks/edit.html.erb
<h1>Stocks#edit</h1>
<p>Find me in app/views/stocks/edit.html.erb</p>

app/views/stocks/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="row" >
    <div id="stock-index-content">
      <div>
        <h3>Stocks Market</h3>
      </div>
      <div>
        <%= form_tag stocks_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control search",
            placeholder: "Find your next investiment!"
          %>
        <% end %>
      </div>
    </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <% @stocks.each do |stock| %>
        <%= link_to stock_path(stock) do %>
          <div class="card-info">
            <div class="d-flex">
              <div class="mr-4">
                <% if stock.photo.file.nil? %>
                  <%= image_tag 'https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png', height: '100px', weigth: '100px' %>
                <% else %>
                  <%= cl_image_tag stock.photo, height: '100px', weigth: '100px' %>
                <% end %>
              </div>
              <div>
                <div class="card-content">
                  <p><%= link_to stock.fullname, stock_path(stock) %></p>
                </div>
                <div class="card-content pb-1">
                  <%= image_tag("money-wallet.png", height: "30", widthth: "30") %>
                  <p style="padding-left: 5px; padding-top: 2px;"><%= stock.price %></p>
                </div>
                <div class="card-content variation">
                  <% if stock.variation.include?('+') %>
                    <div id="variation-positive">
                      <%= stock.variation %>
                    </div>
                  <% else %>
                    <div id="variation-negative">
                      <%= stock.variation %>
                    </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/stocks/show.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="row" >
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div id="show-stocks">
        <div class="card-grande-header">
          <div class="header-info">
            <%= cl_image_tag(@stock.photo, height: "90", width: "90") %>
            <h4><%= @stock.fullname %></h4>
          </div>
          <div class="stock-info">
            <div>
              <%= image_tag("icons8-expensive-price-48(1).png", height: "30", width: "30") %>
              <%= @stock.price %>
            </div>
            <% if @stock.variation.include?('+') %>
              <div id="variation-positive">
                <%= @stock.variation %>
              </div>
            <% else %>
              <div id="variation-negative">
                <%= @stock.variation %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div id="show-stocks">
        <div class="card-grande">
          <div class="wallet-info">
            <div class="stock-quantity">
              <h4 id="stock-quantity"><%= current_user.wallet[@stock.id.to_s] || 0 %></h4>
              <%= image_tag("icons8-gg-48.png", height: "30", width: "30") %>
              </div>
            <div  class="stock-invested">
              <%= image_tag("icons8-expensive-price-48(1).png", height: "30", width: "30") %>
              <h4 id="stock-invested"><%= current_user.wallet[@stock.id.to_s] ? (@stock.price * current_user.wallet[@stock.id.to_s]).round(2) : 0 %></h4>
            </div>
          </div>



          <div class="buy-sell-buttons">
            <div id="button-minus">
              <%= image_tag("arrow_mirrored.png", height: "50", width: "50", style: "transform: rotate(135deg)") %>
              <i class="fas fa-minus-circle"></i>
            </div>
            <div id="button-plus">
              <i class="fas fa-plus-circle"></i>
              <%= image_tag("arrow_mirrored.png", height: "50", width: "50", style: "transform: rotate(-30deg)") %>
            </div>
          </div>


          <div id="btn-credits">
            <div>
              <%= image_tag("icons8-expensive-price-48(1).png", height: "30", width: "30") %>
            </div>
            <div id="user-credits">
              <%= current_user.credits.round(2) %>
            </div>

          </div>
          <!-- <div class="d-flex justify-content-around m-3">
            <div class="btn btn-warning m-2" id="confirm-order" style="color: white; font-weight: bolder;">
              Ok
            </div>
          </div> -->
          <div>
          <%= render 'stocks/new_order', stock: @stock, order: @order %>

          <div class="back-x">
            <%= link_to :back, class: "button-x" do %>
              <%= image_tag "https://cdn3.iconfinder.com/data/icons/interface/100/close_button-512.png" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<%= render 'shared/footer' %>

<%= javascript_tag do %>
  <%= render(partial: 'stocks/quantity', :handlers => [:erb], :formats => [:js]) %>
<% end %>

app/views/stocks/update.html.erb
<h1>Stocks#update</h1>
<p>Find me in app/views/stocks/update.html.erb</p>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form">
        <h2>Edit profile</h2>
          <%= simple_form_for @user do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="form-label-group">
            <div class="form-inputs">
              <%= f.input :name %>
            </div>
          </div>
          <div class="form-inputs">
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
          </div>
            <div class="form-actions">
              <%= f.button :submit, class: "btn btn-lg btn-outline-primary btn-block text-uppercase" %>
            </div>
          <% end %>
          <br>
          <%= link_to 'Back', :back, class: "btn btn-lg btn-outline-dark btn-block text-uppercase" %>
    </div>
  </div>
</div>

app/views/users/_levelbar.js.erb
const outBar = document.getElementById('outbar');
const inBar = document.getElementById('inbar');

const range = '<%= current_user.calculate_range %>';



  console.log(range)
  if (range === "a") {
    outbar.classList.add("progress2", "progress-moved_a")
    inbar.classList.add("progress-bar2_a")
  } else if (range === "b") {
    outbar.classList.add("progress2", "progress-moved_b")
    inbar.classList.add("progress-bar2_b")
  } else if (range === "c") {
    outbar.classList.add("progress2", "progress-moved_c")
    inbar.classList.add("progress-bar2_c")
  } else {
    outbar.classList.add("progress2", "progress-moved_d")
    inbar.classList.add("progress-bar2_d")
  };

app/views/users/dashboard.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="row" >
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="card-info-dashboard mt-3" id="dashboard-head">
         <h4 class="ml-3 mb-3">Hello, @<%= current_user.username %>!</h4>
         <p class="ml-3" style="margin-top: -15px;">Trader since <%= current_user.created_at.strftime("%B %Y") %></p>
            <div class="container">
              <div id="outbar">
                <div id="inbar">
                </div>
              </div>
              <p>XP <%= current_user.experience %>/<%= current_user.calculate_maxhp %></p>
              <h5>Level <%= current_user.calculate_level %></h5>
              <h5>Rank: <%= current_user.ranking %>º</h5>
            </div>
          </div>
        </div>
    <div class="col-xs-12 col-sm-4 col-sm-offset-4" id="dashboard-1">
      <div class="card-info-dashboard">
       <span style="color: #FF9EE2; margin-bottom: -30px"> ● ● ● ● ● ● ● ● ● ● ● ● </span>
       <section class="grid-container" style="margin-bottom: -20px;">
        <div class="box" id="box">
          <h4 style="color: #9E1633">TOTAL !</h4>
          <div class="card-content-dashboard justify-content-center">
            <%= image_tag("money-dashboard3.png", height: "30", width: "30") %>
            <p><%= current_user.total.round(2) %></p>
          </div>
        </div>
      </section>
      <span style="margin-left: 160px; color: #FF9EE2; margin-top: -15px">● ● ● ● ● ● ● ● ● ● ● ● </span>
      </div>
    </div>
    <%= link_to dashboard_wallet_path do %>
    <div class="col-xs-12 col-sm-4 col-sm-offset-4 ml-2" id="dashboard">
      <div class="card-info-dashboard">
       <span style="color: #1AC8ED; margin-bottom: -30px"> ● ● ● ● ● ● ● ● ● ● ● ● </span>
       <section class="grid-container" style="margin-bottom: -20px;">
        <div class="box" id="box-2">
          <h4>Invested</h4>
          <div class="card-content-dashboard justify-content-center">
            <%= image_tag("money-dashboard.png", height: "30", width: "30") %>
            <p><%= invested_credits = current_user.invested_credits.round(2) %></p>
          </div>
        </div>
      </section>
      <span style="margin-left: 160px; color: #1AC8ED; margin-top: -15px;"> ● ● ● ● ● ● ● ● ● ● ● ● </span>
    </div>
  </div>
  <% end %>
  <%= link_to stocks_path do %>
  <div class="col-xs-12 col-sm-4 col-sm-offset-4 ml-2">
    <div class="card-info-dashboard" id="dashboard">
     <span  style="color: #EEBA0B; margin-bottom: -30px"> ● ● ● ● ● ● ● ● ● ● ● ● </span>
     <section class="grid-container" style="margin-bottom: -20px;">
      <div class="box" id="box-3" >
        <h4> Available</h4>
        <div class="card-content-dashboard justify-content-center">
          <%= image_tag("money-dashboard2.png", height: "30", width: "30") %>
          <p><%= current_user.credits.round(2) %></p>
        </div>
      </div>
    </section>
    <span style="margin-left: 160px; color: #EEBA0B; margin-top: -15px;"> ● ● ● ● ● ● ● ● ● ● ● ● </span>
  </div>
</div>
<% end %>

      <!-- card 2: conquistas
      infos, quanto ja investiu
      etc -->
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

<%= javascript_tag do %>
<%= render(:partial => 'levelbar', :handlers => [:erb], :formats => [:js]) %>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/user_wallet.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="row" >
    <div id="stock-index-content">
      <div>
        <h3>Wallet</h3>
      </div>
      <div>
        <p>Check your investiments</p>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="card-info" id="wallet">
        <div class="card-content">
         <% if current_user.number_of_stocks == 1 %>
            <p>YAY! You own <%= "#{current_user.number_of_stocks}" %> stock.</p>
            <i class="fas fa-smile-beam"></i>
          <% elsif current_user.number_of_stocks <= 0 %>
            <p>Oops, you don't own any stocks...</p>
            <i class="fas fa-sad-cry"></i>
          <% else %>
            <p>YAY! You own <%= "#{current_user.number_of_stocks}" %> stocks!</p>
            <i class="fas fa-laugh-beam"></i>
          <% end %>
        </div>
        <div class="card-content">
          <p>Invested: <%= current_user.invested_credits.round(2) %></p>
        </div>
        <div class="card-content" id="evolution">
          <p>Evolution:</p>
           <% if current_user.evolution >= 0 %>
              <p id="variation-positive"><%= "+#{current_user.evolution.round(2)}%" %></p>
           <% else %>
              <p id="variation-negative"><%= "#{current_user.evolution.round(2)}%" %></p>
          <% end %>
        </div>
      </div>
        <% @wallet.each do |key, value| %>
        <% if value > 0 %>
        <% stock = Stock.find(key.to_i) %>
         <%= link_to stock_path(stock) do %>
        <div class="card-info">
          <div class="d-flex align-items-center">
            <div class="mr-4">
              <% if stock.photo.file.nil? %>
              <%= image_tag 'https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png', height: '100px', weigth: '100px' %>
              <% else %>
              <%= cl_image_tag stock.photo, height: '100px', weigth: '100px' %>
              <% end %>
            </div>
            <div>
              <div class="card-content">
                <p><%= link_to stock.fullname, stock_path(stock) %></p>
              </div>
              <div class="card-content">

                  <%= image_tag("money-wallet.png", height: "30", width: "30") %>
                  <p class="coin-p"><%= stock.price %></p>
                </div>
                  <div class="card-content">
                    <p>Quantity:</p> <p><%= value %></p>
                  </div>
                  <div class="card-content">
                    <% if stock.variation.include?('+') %>
                    <div id="variation-positive">
                      <%= stock.variation %>
                    </div>
                    <% else %>
                    <div id="variation-negative">
                      <%= stock.variation %>
                    </div>
                    <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>